import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
       <div className="navbar">
        <Link href="/">HOME</Link>
        <Link href="/login">LOGIN</Link>
        <Link href="/menu">MENU</Link>
        <Link href="/product">PRODUCT</Link>
      </div>
      {children}
      </body>
    </html>
  )
}
