import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'DyaByaApp',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className='root'>
          <div className="navbar">
           <div className='home'><Link href="/">DyaBya</Link></div>
            </div>
             <div className='bangg'>
          {/* <div className='box'><Link href="/list">List</Link></div>
          <div className='box'><Link href="/registeration">Registration</Link></div>
          <div className='box'><Link href="/management">Management</Link></div>
          <div className='box'><Link href="/usermanagement">User-management</Link></div> */}
          {children}
        </div>
       </div>
      </body>
    </html>
  )
}
